### PR TITLE
Include stack in error proplist

### PR DESCRIPTION
**Pull request by gleber**
It does few other minor changes like adding ?is_v8 macro, adding Array:unpush/1 and Object:copy_properties_to/1

### CODE REVIEW

**Comment by yrashk** [comment]
does copy_properties_to really belong there?

**Comment by gleber** [comment]
It doesn't have to be there, but it is very useful :) I've replaced at least three instances of lists:foreach over Object:proplist doing Copy:set_value in beamjs with this one.

**Comment by yrashk** [comment]
Can we move it to some "utility module"?

**Comment by gleber** [comment]
In utility module it would not be as useful, but I get that copy_properties_to in object doesn't fit the way it works in JS. I'll move it

**Comment by gleber** [comment]
Moved them to erlv8_utils

**Comment by yrashk** [comment]
Thanks!

**Pull request merged**
